//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHMUP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SHMUP.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awards.
        /// </summary>
        internal static string Awards {
            get {
                return ResourceManager.GetString("Awards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award Unlocked.
        /// </summary>
        internal static string AwardUnlocked {
            get {
                return ResourceManager.GetString("AwardUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender.
        /// </summary>
        internal static string AwdDefender {
            get {
                return ResourceManager.GetString("AwdDefender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gained 10x Multiplier..
        /// </summary>
        internal static string AwdDefenderDescription {
            get {
                return ResourceManager.GetString("AwdDefenderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Spender.
        /// </summary>
        internal static string AwdMaxEverything {
            get {
                return ResourceManager.GetString("AwdMaxEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bought everything at the shop..
        /// </summary>
        internal static string AwdMaxEverythingDesc {
            get {
                return ResourceManager.GetString("AwdMaxEverythingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully Loaded.
        /// </summary>
        internal static string AwdMaxWeapons {
            get {
                return ResourceManager.GetString("AwdMaxWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bought all the weapons upgrades..
        /// </summary>
        internal static string AwdMaxWeaponsDesc {
            get {
                return ResourceManager.GetString("AwdMaxWeaponsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballistophobic.
        /// </summary>
        internal static string AwdNoMiss {
            get {
                return ResourceManager.GetString("AwdNoMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished a level without using missiles..
        /// </summary>
        internal static string AwdNoMissDisc {
            get {
                return ResourceManager.GetString("AwdNoMissDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snowball In Hell.
        /// </summary>
        internal static string AwdOneShip {
            get {
                return ResourceManager.GetString("AwdOneShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished a level with one ship left..
        /// </summary>
        internal static string AwdOneShipDesc {
            get {
                return ResourceManager.GetString("AwdOneShipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninja.
        /// </summary>
        internal static string AwdShipNotDied {
            get {
                return ResourceManager.GetString("AwdShipNotDied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished a level without enemies destroying any of your ships..
        /// </summary>
        internal static string AwdShipNotDiedDesc {
            get {
                return ResourceManager.GetString("AwdShipNotDiedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Ninja.
        /// </summary>
        internal static string AwdShipNotHit {
            get {
                return ResourceManager.GetString("AwdShipNotHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished a level without an enemy hitting any of your ships..
        /// </summary>
        internal static string AwdShipNotHitDesc {
            get {
                return ResourceManager.GetString("AwdShipNotHitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigilant Defender.
        /// </summary>
        internal static string AwdWallNotHIt {
            get {
                return ResourceManager.GetString("AwdWallNotHIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished a level without an enemy hitting the wall..
        /// </summary>
        internal static string AwdWallNotHItDesc {
            get {
                return ResourceManager.GetString("AwdWallNotHItDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Health.
        /// </summary>
        internal static string BuffHealth {
            get {
                return ResourceManager.GetString("BuffHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Speed.
        /// </summary>
        internal static string BuffSpeed {
            get {
                return ResourceManager.GetString("BuffSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet Upgrades.
        /// </summary>
        internal static string BulletMenu {
            get {
                return ResourceManager.GetString("BulletMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press a button to continue!.
        /// </summary>
        internal static string ButtonToContinue {
            get {
                return ResourceManager.GetString("ButtonToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Connect to.
        /// </summary>
        internal static string CannotConnet {
            get {
                return ResourceManager.GetString("CannotConnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Player.
        /// </summary>
        internal static string ChangePlayer {
            get {
                return ResourceManager.GetString("ChangePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor Speed.
        /// </summary>
        internal static string CursorSpeed {
            get {
                return ResourceManager.GetString("CursorSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Finished.
        /// </summary>
        internal static string DemoFinished {
            get {
                return ResourceManager.GetString("DemoFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey there! I hope you enjoyed the S.H.M.U.P demo!.
        /// </summary>
        internal static string DemoOut1 {
            get {
                return ResourceManager.GetString("DemoOut1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;ve enjoyed these 4 levels, the full version has 19.
        /// </summary>
        internal static string DemoOut2 {
            get {
                return ResourceManager.GetString("DemoOut2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to go to the store!.
        /// </summary>
        internal static string DemoOut3 {
            get {
                return ResourceManager.GetString("DemoOut3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and increased limits on the upgrades!.
        /// </summary>
        internal static string DemoOut4 {
            get {
                return ResourceManager.GetString("DemoOut4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty Rating.
        /// </summary>
        internal static string DiffRate {
            get {
                return ResourceManager.GetString("DiffRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects Volume.
        /// </summary>
        internal static string EffectsVolume {
            get {
                return ResourceManager.GetString("EffectsVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Game.
        /// </summary>
        internal static string ExitGame {
            get {
                return ResourceManager.GetString("ExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award 50% complete.
        /// </summary>
        internal static string FiftyPercent {
            get {
                return ResourceManager.GetString("FiftyPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure to buy upgrades between levels or you will be unable to finish the first level!.
        /// </summary>
        internal static string FinTutorial {
            get {
                return ResourceManager.GetString("FinTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        internal static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over.
        /// </summary>
        internal static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global High Scores.
        /// </summary>
        internal static string globalHighScores {
            get {
                return ResourceManager.GetString("globalHighScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100Pickups.
        /// </summary>
        internal static string Got100Pickups {
            get {
                return ResourceManager.GetString("Got100Pickups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collected 100 Pickups..
        /// </summary>
        internal static string Got100PickupsDesc {
            get {
                return ResourceManager.GetString("Got100PickupsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10kPickups.
        /// </summary>
        internal static string Got10kPickups {
            get {
                return ResourceManager.GetString("Got10kPickups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collected 10,000 Pickups.
        /// </summary>
        internal static string Got10kPickupsDesc {
            get {
                return ResourceManager.GetString("Got10kPickupsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1kPickups.
        /// </summary>
        internal static string Got1kPickups {
            get {
                return ResourceManager.GetString("Got1kPickups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collected 1,000 Pickps.
        /// </summary>
        internal static string Got1kPickupsDesc {
            get {
                return ResourceManager.GetString("Got1kPickupsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #SHMUP.
        /// </summary>
        internal static string HashTag {
            get {
                return ResourceManager.GetString("HashTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Scores.
        /// </summary>
        internal static string HighScores {
            get {
                return ResourceManager.GetString("HighScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to IndieCity.
        /// </summary>
        internal static string ICconnect {
            get {
                return ResourceManager.GetString("ICconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid awards file, rebuilding..
        /// </summary>
        internal static string InvalidAwards {
            get {
                return ResourceManager.GetString("InvalidAwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invaild high score file, rebuilding..
        /// </summary>
        internal static string InvalidHighScore {
            get {
                return ResourceManager.GetString("InvalidHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid save file, rebuilding..
        /// </summary>
        internal static string InvalidSaveGame {
            get {
                return ResourceManager.GetString("InvalidSaveGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.H.M.U.P Commodore.
        /// </summary>
        internal static string Killed100k {
            get {
                return ResourceManager.GetString("Killed100k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed 100,00 enemies..
        /// </summary>
        internal static string Killed100kDescription {
            get {
                return ResourceManager.GetString("Killed100kDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.H.M.U.P Captain.
        /// </summary>
        internal static string Killed10k {
            get {
                return ResourceManager.GetString("Killed10k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed 10,000 enemies..
        /// </summary>
        internal static string Killed10kDescription {
            get {
                return ResourceManager.GetString("Killed10kDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.H.M.U.P Lieutenant.
        /// </summary>
        internal static string Killed1k {
            get {
                return ResourceManager.GetString("Killed1k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed 1,000 enemies..
        /// </summary>
        internal static string Killed1kDescription {
            get {
                return ResourceManager.GetString("Killed1kDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.H.M.U.P Admiral.
        /// </summary>
        internal static string Killed500k {
            get {
                return ResourceManager.GetString("Killed500k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed 500,000 enemies..
        /// </summary>
        internal static string Killed500kDescription {
            get {
                return ResourceManager.GetString("Killed500kDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.H.M.U.P Commander.
        /// </summary>
        internal static string Killed5k {
            get {
                return ResourceManager.GetString("Killed5k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed 5,000 enemies..
        /// </summary>
        internal static string Killed5kDescription {
            get {
                return ResourceManager.GetString("Killed5kDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 2 Finished!.
        /// </summary>
        internal static string L1Finished {
            get {
                return ResourceManager.GetString("L1Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to levels.
        /// </summary>
        internal static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Sequence.
        /// </summary>
        internal static string LevelSequence {
            get {
                return ResourceManager.GetString("LevelSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels not loaded..
        /// </summary>
        internal static string LevelsNoExist {
            get {
                return ResourceManager.GetString("LevelsNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Scores.
        /// </summary>
        internal static string localHighScores {
            get {
                return ResourceManager.GetString("localHighScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Player.
        /// </summary>
        internal static string LoggedInAs {
            get {
                return ResourceManager.GetString("LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login cannot be empty..
        /// </summary>
        internal static string LoginEmpty {
            get {
                return ResourceManager.GetString("LoginEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging into Twitter.
        /// </summary>
        internal static string LogingInTwitter {
            get {
                return ResourceManager.GetString("LogingInTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1.
        /// </summary>
        internal static string LVL1_1 {
            get {
                return ResourceManager.GetString("LVL1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Zone.
        /// </summary>
        internal static string LVL1_2 {
            get {
                return ResourceManager.GetString("LVL1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 2.
        /// </summary>
        internal static string LVL2_1 {
            get {
                return ResourceManager.GetString("LVL2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iSector.
        /// </summary>
        internal static string LVL2_2 {
            get {
                return ResourceManager.GetString("LVL2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string Mid {
            get {
                return ResourceManager.GetString("Mid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missile Bank.
        /// </summary>
        internal static string MissileBank {
            get {
                return ResourceManager.GetString("MissileBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missile Strength.
        /// </summary>
        internal static string MissileStrength {
            get {
                return ResourceManager.GetString("MissileStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Awards.
        /// </summary>
        internal static string MoreAwards {
            get {
                return ResourceManager.GetString("MoreAwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Volume.
        /// </summary>
        internal static string MusicVolume {
            get {
                return ResourceManager.GetString("MusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created new awards file..
        /// </summary>
        internal static string NewAwards {
            get {
                return ResourceManager.GetString("NewAwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New High Score!.
        /// </summary>
        internal static string NewHighScore {
            get {
                return ResourceManager.GetString("NewHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created new save file..
        /// </summary>
        internal static string NewSave {
            get {
                return ResourceManager.GetString("NewSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created new high score file..
        /// </summary>
        internal static string NoHighScore {
            get {
                return ResourceManager.GetString("NoHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not In Demo.
        /// </summary>
        internal static string Notindemo {
            get {
                return ResourceManager.GetString("Notindemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not signed in..
        /// </summary>
        internal static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in, cannot save..
        /// </summary>
        internal static string NotLoggedInSaveFail {
            get {
                return ResourceManager.GetString("NotLoggedInSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Ships.
        /// </summary>
        internal static string NumberBuffs {
            get {
                return ResourceManager.GetString("NumberBuffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Game Finished.
        /// </summary>
        internal static string orgFin {
            get {
                return ResourceManager.GetString("orgFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Game.
        /// </summary>
        internal static string OriginalGame {
            get {
                return ResourceManager.GetString("OriginalGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Upgrades.
        /// </summary>
        internal static string OtherMenu {
            get {
                return ResourceManager.GetString("OtherMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle Modifier.
        /// </summary>
        internal static string ParticleMod {
            get {
                return ResourceManager.GetString("ParticleMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty..
        /// </summary>
        internal static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Score.
        /// </summary>
        internal static string personHigh {
            get {
                return ResourceManager.GetString("personHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Ups.
        /// </summary>
        internal static string PickUpRate {
            get {
                return ResourceManager.GetString("PickUpRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name: .
        /// </summary>
        internal static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points To Spend.
        /// </summary>
        internal static string PointsToSpend {
            get {
                return ResourceManager.GetString("PointsToSpend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Pocess Quality.
        /// </summary>
        internal static string PostProcess {
            get {
                return ResourceManager.GetString("PostProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Levels.
        /// </summary>
        internal static string RandomGame {
            get {
                return ResourceManager.GetString("RandomGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Finished.
        /// </summary>
        internal static string SeqFin {
            get {
                return ResourceManager.GetString("SeqFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award 75% complete.
        /// </summary>
        internal static string SeventyFivePercent {
            get {
                return ResourceManager.GetString("SeventyFivePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall Strength.
        /// </summary>
        internal static string ShieldStrength {
            get {
                return ResourceManager.GetString("ShieldStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Upgrades.
        /// </summary>
        internal static string ShipMenu {
            get {
                return ResourceManager.GetString("ShipMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.H.M.U.P.
        /// </summary>
        internal static string SHMUP {
            get {
                return ResourceManager.GetString("SHMUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shooting Speed.
        /// </summary>
        internal static string ShootSpeed {
            get {
                return ResourceManager.GetString("ShootSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        internal static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives your ships more missiles to fire..
        /// </summary>
        internal static string ShopBulletMisNum {
            get {
                return ResourceManager.GetString("ShopBulletMisNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes your ships&apos; missiles deal more damage to the enemy..
        /// </summary>
        internal static string ShopBulletMisStr {
            get {
                return ResourceManager.GetString("ShopBulletMisStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows your ships to fire their main gun faster..
        /// </summary>
        internal static string ShopBulletSpeed {
            get {
                return ResourceManager.GetString("ShopBulletSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the chance of enemies dropping pickups..
        /// </summary>
        internal static string ShopOtherPickups {
            get {
                return ResourceManager.GetString("ShopOtherPickups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes your wall stronger, by giving more shields and adding another section..
        /// </summary>
        internal static string ShopOtherWall {
            get {
                return ResourceManager.GetString("ShopOtherWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows your ships to take more damage before exploding..
        /// </summary>
        internal static string ShopShipHealth {
            get {
                return ResourceManager.GetString("ShopShipHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds another ship to your fleet..
        /// </summary>
        internal static string ShopShipNumber {
            get {
                return ResourceManager.GetString("ShopShipNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes your ships move towards your cursor faster..
        /// </summary>
        internal static string ShopShipSpeed {
            get {
                return ResourceManager.GetString("ShopShipSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missile Master.
        /// </summary>
        internal static string Shot100kMissiles {
            get {
                return ResourceManager.GetString("Shot100kMissiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shot 100,000 missiles..
        /// </summary>
        internal static string Shot100kMissilesDesc {
            get {
                return ResourceManager.GetString("Shot100kMissilesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOM!.
        /// </summary>
        internal static string Shot10kMissiles {
            get {
                return ResourceManager.GetString("Shot10kMissiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shot 10,000 missiles..
        /// </summary>
        internal static string Shot10kMissilesDesc {
            get {
                return ResourceManager.GetString("Shot10kMissilesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boom!.
        /// </summary>
        internal static string Shot1kMissiles {
            get {
                return ResourceManager.GetString("Shot1kMissiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shot 1,000 missiles..
        /// </summary>
        internal static string Shot1kMissilesDesc {
            get {
                return ResourceManager.GetString("Shot1kMissilesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KaBOOM!.
        /// </summary>
        internal static string Shot50kMissiles {
            get {
                return ResourceManager.GetString("Shot50kMissiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shot 50,000 missiles..
        /// </summary>
        internal static string Shot50kMissilesDesc {
            get {
                return ResourceManager.GetString("Shot50kMissilesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Level: .
        /// </summary>
        internal static string SingleLevel {
            get {
                return ResourceManager.GetString("SingleLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn Speed Multiplier.
        /// </summary>
        internal static string SpawnSpeed {
            get {
                return ResourceManager.GetString("SpawnSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        internal static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Level.
        /// </summary>
        internal static string StartLevel {
            get {
                return ResourceManager.GetString("StartLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award 10% complete.
        /// </summary>
        internal static string TenPercent {
            get {
                return ResourceManager.GetString("TenPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the start of a new level, you get a new supply of missiles..
        /// </summary>
        internal static string Tip1 {
            get {
                return ResourceManager.GetString("Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The more points an enemy has, the harder it is and the more points you earn for killing it!.
        /// </summary>
        internal static string Tip10 {
            get {
                return ResourceManager.GetString("Tip10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ships&apos; shields will recharge if they aren&apos;t hit for a short time..
        /// </summary>
        internal static string Tip11 {
            get {
                return ResourceManager.GetString("Tip11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ships have shields that can destroy multiple enemies before destroying your ship..
        /// </summary>
        internal static string Tip2 {
            get {
                return ResourceManager.GetString("Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have the points, buying a new ship is always the best option..
        /// </summary>
        internal static string Tip3 {
            get {
                return ResourceManager.GetString("Tip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure to check out the modding tools at charcoalstyles.com/SHMUP.
        /// </summary>
        internal static string Tip4 {
            get {
                return ResourceManager.GetString("Tip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the spawn rate at the start of a level not only makes the level harder, but gives you more points..
        /// </summary>
        internal static string Tip5 {
            get {
                return ResourceManager.GetString("Tip5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As you damage bosses, they start to move faster..
        /// </summary>
        internal static string Tip6 {
            get {
                return ResourceManager.GetString("Tip6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remeber to upgrade your wall. It&apos;s your last, best defence!.
        /// </summary>
        internal static string Tip7 {
            get {
                return ResourceManager.GetString("Tip7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell me what you think of the game: aaron@charcoalstyles.com.
        /// </summary>
        internal static string Tip8 {
            get {
                return ResourceManager.GetString("Tip8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;re having trouble with a level, play some other levels to earn more points and buy more upgrades!.
        /// </summary>
        internal static string Tip9 {
            get {
                return ResourceManager.GetString("Tip9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointacular!.
        /// </summary>
        internal static string Total100mPoints {
            get {
                return ResourceManager.GetString("Total100mPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gained over 100,000,000 Points..
        /// </summary>
        internal static string Total100mPointsDescription {
            get {
                return ResourceManager.GetString("Total100mPointsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointastic!.
        /// </summary>
        internal static string Total10mPoints {
            get {
                return ResourceManager.GetString("Total10mPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gained over 10,000,000 Points..
        /// </summary>
        internal static string Total10mPointsDescription {
            get {
                return ResourceManager.GetString("Total10mPointsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointriffic!.
        /// </summary>
        internal static string Total50mPoints {
            get {
                return ResourceManager.GetString("Total50mPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gained over 50,000,000 Points..
        /// </summary>
        internal static string Total50mPointsDescription {
            get {
                return ResourceManager.GetString("Total50mPointsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Enemies Destroyed.
        /// </summary>
        internal static string TotalKills {
            get {
                return ResourceManager.GetString("TotalKills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Levels Completed.
        /// </summary>
        internal static string TotalLevelsCompletes {
            get {
                return ResourceManager.GetString("TotalLevelsCompletes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Missiles Fired.
        /// </summary>
        internal static string TotalMissiles {
            get {
                return ResourceManager.GetString("TotalMissiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Pickups Collected.
        /// </summary>
        internal static string TotalPickups {
            get {
                return ResourceManager.GetString("TotalPickups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Points Scored.
        /// </summary>
        internal static string TotalScore {
            get {
                return ResourceManager.GetString("TotalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Mouse to move the cursor..
        /// </summary>
        internal static string TUT_0k {
            get {
                return ResourceManager.GetString("TUT_0k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Left Stick to move the cursor..
        /// </summary>
        internal static string TUT_0p {
            get {
                return ResourceManager.GetString("TUT_0p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ships will move to the cursor..
        /// </summary>
        internal static string TUT_1 {
            get {
                return ResourceManager.GetString("TUT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Red Pickup slows down your enemies..
        /// </summary>
        internal static string TUT_10 {
            get {
                return ResourceManager.GetString("TUT_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After each level, you can spend points on upgrades..
        /// </summary>
        internal static string TUT_11 {
            get {
                return ResourceManager.GetString("TUT_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ships will shoot automatically..
        /// </summary>
        internal static string TUT_2k {
            get {
                return ResourceManager.GetString("TUT_2k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ships will shoot automatically..
        /// </summary>
        internal static string TUT_2p {
            get {
                return ResourceManager.GetString("TUT_2p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use either Mouse Button to fire missiles..
        /// </summary>
        internal static string TUT_3k {
            get {
                return ResourceManager.GetString("TUT_3k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use any Button to fire missiles..
        /// </summary>
        internal static string TUT_3p {
            get {
                return ResourceManager.GetString("TUT_3p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a limited amount of missiles per level..
        /// </summary>
        internal static string TUT_4 {
            get {
                return ResourceManager.GetString("TUT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemies that damage the wall are teleported back..
        /// </summary>
        internal static string TUT_5 {
            get {
                return ResourceManager.GetString("TUT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the wall is damaged enough, it will break..
        /// </summary>
        internal static string TUT_6 {
            get {
                return ResourceManager.GetString("TUT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an enemy makes it through the wall, your game ends..
        /// </summary>
        internal static string TUT_7 {
            get {
                return ResourceManager.GetString("TUT_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Green Pickup gives you more missiles..
        /// </summary>
        internal static string TUT_8 {
            get {
                return ResourceManager.GetString("TUT_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Blue Pickup repairs your wall..
        /// </summary>
        internal static string TUT_9 {
            get {
                return ResourceManager.GetString("TUT_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award 25% complete.
        /// </summary>
        internal static string TwentyFivePercent {
            get {
                return ResourceManager.GetString("TwentyFivePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Login Failed.
        /// </summary>
        internal static string TwitterLoginFail {
            get {
                return ResourceManager.GetString("TwitterLoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Login Successful.
        /// </summary>
        internal static string TwitterLoginSuccess {
            get {
                return ResourceManager.GetString("TwitterLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TwitterMultipleAwards {
            get {
                return ResourceManager.GetString("TwitterMultipleAwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Award: .
        /// </summary>
        internal static string TwitterNewAward {
            get {
                return ResourceManager.GetString("TwitterNewAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  New Awards..
        /// </summary>
        internal static string TwitterNewAwards {
            get {
                return ResourceManager.GetString("TwitterNewAwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Highscore:.
        /// </summary>
        internal static string TwitterNewHighScore {
            get {
                return ResourceManager.GetString("TwitterNewHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.H.M.U.P will post about awards you unlock and your high scores..
        /// </summary>
        internal static string TwitterTip1 {
            get {
                return ResourceManager.GetString("TwitterTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generally, posts will only go out once every five munites..
        /// </summary>
        internal static string TwitterTip2 {
            get {
                return ResourceManager.GetString("TwitterTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t want to participate with Twitter, please click on skip..
        /// </summary>
        internal static string TwitterTip3 {
            get {
                return ResourceManager.GetString("TwitterTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultra.
        /// </summary>
        internal static string Ultra {
            get {
                return ResourceManager.GetString("Ultra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure You Want To Exit?.
        /// </summary>
        internal static string WantToExit {
            get {
                return ResourceManager.GetString("WantToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Score.
        /// </summary>
        internal static string YourScore {
            get {
                return ResourceManager.GetString("YourScore", resourceCulture);
            }
        }
    }
}
